<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_jodconverter_menu() {
  return array(
    'admin/islandora/jodcoverter' => array(
      'title' => 'JODConverter',
      'description' => 'Configure the JODConverter.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_jodconverter_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    )
  );
}

/**
 * Convert a document and get the output message.
 * 
 * @param string $from
 *   Convert from path.
 * @param string $to
 *   Convert to path.
 * @param string $type
 *   convert to type.
 * 
 * @return string
 *   Output message.
 */
function islandora_jodconverter_convert($from, $to = NULL, $type = NULL) {
  module_load_include('inc', 'islandora_jodconverter', 'includes/utilities');
  $command = '';
  // @todo validate extension or type is using.
  $ext = islandora_jodconverter_get_ext($from);
  if(!$ext)
  {
    watchdog('JODConverter', 'The original do not have an extension', NULL, WATCHDOG_ERROR);
    drupal_set_message(t('The original do not have an extension'), 'error');
  }
  else {
    $toformat = islandora_jodconverter_get_format($ext);
    $to_ext = '';
    
    // Get the to extensions
    if ($to) {
      $to_ext = islandora_jodconverter_get_ext($to);
    }
    else {
      $to_ext = strtolower($type);
    }
    if(!in_array($to_ext, $toformat['to'])) {
      watchdog('JODConverter', 'The original can not be converted to the new format', NULL, WATCHDOG_ERROR);
      drupal_set_message(t('The original can not be converted to the new format'), 'error');
    }
  }
  
  if(!$to && !$type)
  {
    watchdog('JODConverter', 'Convert type undefined', NULL, WATCHDOG_ERROR);
    drupal_set_message(t('Convert type undefined'), 'error');
  }
  elseif ($to) {
    $command = "$from $to";
  }
  else{
    $command = "-f $type $from ";
  }
  $message = islandora_jodconverter_exec_convert($command);
  if (count($message) == 4 && $message[1] == 'INFO: connected' && $message[3] == 'INFO: disconnected') {
    $output = 'SUCCESS';
  }
  else {
    $output = implode("\n", $message);
    watchdog('JODConverter', "Convert Fail of %from.\nWith message: \n %message", array('%from' => $from, '%message' => $output), WATCHDOG_ERROR);
    drupal_set_message(t("Convert Fail of %from.\nWith message: \n %message", array('%from' => $from, '%message' => $output)),'error');
  }
  return $output;
}
